## Find duplicated columns:

In [ ]:
dup_cols = {}

for i, c1 in enumerate(tqdm_notebook(train_enc.columns)):
    for c2 in train_enc.columns[i + 1:]:
        if c2 not in dup_cols and np.all(train_enc[c1] == train_enc[c2]):
            dup_cols[c2] = c1

In [ ]:
import cPickle as pickle
pickle.dump(dup_cols, open('dup_cols.p', 'w'), protocol=pickle.HIGHEST_PROTOCOL)
traintest.drop(dup_cols.keys(), axis = 1,inplace=True)

## Unique values

In [ ]:
nunique = train.nunique(dropna=False)
plt.figure(figsize=(14,6))
_ = plt.hist(nunique.astype(float)/train.shape[0], bins=100)

## Split categorical/numerical

In [ ]:
cat_cols = list(train.select_dtypes(include=['object']).columns)
num_cols = list(train.select_dtypes(exclude=['object']).columns)

In [ ]:
train.loc[:,cat_cols].head().T

## Validation schemes

a) Holdout scheme:

Split train data into two parts: partA and partB.
Fit the model on partA, predict for partB.
Use predictions for partB for estimating model quality. Find such hyper-parameters, that quality on partB is maximized.

b) K-Fold scheme:

Split train data into K folds.
Iterate though each fold: retrain the model on all folds except current fold, predict for the current fold.
Use the predictions to calculate quality on each fold. Find such hyper-parameters, that quality on each fold is maximized. You can also estimate mean and variance of the loss. This is very helpful in order to understand significance of improvement.

c) LOO (Leave-One-Out) scheme:

Iterate over samples: retrain the model on all samples except current sample, predict for the current sample. You will need to retrain the model N times (if N is the number of samples in the dataset).
In the end you will get LOO predictions for every sample in the trainset and can calculate loss.

Stratification


## Flatten images and standardize

In [ ]:
# Reshape the training and test examples 
train_x_flatten = train_x_orig.reshape(train_x_orig.shape[0], -1).T   # The "-1" makes reshape flatten the remaining dimensions
test_x_flatten = test_x_orig.reshape(test_x_orig.shape[0], -1).T

# Standardize data to have feature values between 0 and 1.
train_x = train_x_flatten/255.
test_x = test_x_flatten/255.

## Sparse matrices

In [2]:
from scipy import sparse
from numpy import array
I = array([0,3,1,0])
J = array([0,3,1,2])
V = array([4,5,7,9])
A =sparse.coo_matrix((V,(I,J)),shape=(4,4))
A.todense()

matrix([[4, 0, 9, 0],
        [0, 7, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 5]])

In [39]:
nb=4
I = array([1,2,1,3])
J = array([0,3,2,0])
V = np.ones(nb)
A =sparse.coo_matrix((V,(I,J)),shape=(nb, nb))
print(A.toarray())
A = A.tocsr()

[[ 0.  0.  0.  0.]
 [ 1.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]]


In [40]:
A[I, :].todense()

matrix([[ 1.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 1.,  0.,  1.,  0.],
        [ 1.,  0.,  0.,  0.]])

In [41]:
A[J, :].todense()

matrix([[ 0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.]])

In [42]:
A[I, :].multiply(A[J, :]).todense()

matrix([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])

In [21]:
A =sparse.coo_matrix((V,(I,J)),shape=(nb, nb))
print(A.toarray())
np.unique(A.toarray())

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  2.]]


array([ 0.,  1.,  2.])

In [24]:
L = 1.01 
C = 0.3
((-L - np.log( 1 - C )) /(np.log(C)- np.log( 1 - C)))

0.77106893172456126